export const COFFEES_LOADING = 'COFFEES_LOADING';
export const ADD_COFFEES = 'ADD_COFFEES';
export const COFFEES_FAILED = 'COFFEES_FAILED';

export const COFFEE_TYPES_LOADING = 'COFFEE_TYPES_LOADING';
export const ADD_COFFEE_TYPES = 'ADD_COFFEE_TYPES';
export const COFFEE_TYPES_FAILED = 'COFFEE_TYPES_FAILED';

export const LEARN_MORE_LOADING = 'LEARN_MORE_LOADING';
export const ADD_LEARN_MORE = 'ADD_LEARN_MORE';
export const LEARN_MORE_FAILED = 'LEARN_MORE_FAILED';

